server:
  port: 8081
  context-path: /leagues
security.user.password: testme
#security.user.password: dinesh
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3304/league
    username: root
    password: '{cipher}61156bd365666251d14678ae874fa78ded10711676e136385bf835a867664b02' #admin123
    driver-class-name: com.mysql.jdbc.Driver
security:
  oauth2:
    resource:
      jwt:
        key-uri: ${vcap.services.auth-token-key.credentials.uri:http://localhost:9999/auth/oauth/token_key}
#      userInfoUri: http://localhost:9999/auth/user
logging:
  level:
    com.makeurpicks: DEBUG
#    org.springframework.security: DEBUG
